# Generated by Django 6.1.1 on 2026-09-08 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('GS', 'General Shift (12:00 PM - 9:00 PM)'), ('NS', 'Night Shift (9:30 PM - 6:30 AM)')], default='GS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('shift', models.CharField(choices=[('GS', 'General Shift'), ('NS', 'Night Shift')], max_length=10)),
                ('punch_in', models.DateTimeField()),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('first_half', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent')], default='AB', max_length=5)),
                ('second_half', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent')], default='AB', max_length=5)),
                ('total_worked_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('IN', 'Punched In'), ('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent')], default='IN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-attendance_date', '-punch_in'],
            },
        ),
    ]
