# Generated by Django 6.1.1 on 2026-09-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'attendance_date')},
        ),
    ]
